package Talk;

/**
* Talk/AfficherMessageHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Talk.idl
* jeudi 3 novembre 2016 18 h 40 CET
*/

public final class AfficherMessageHolder implements org.omg.CORBA.portable.Streamable
{
  public Talk.AfficherMessage value = null;

  public AfficherMessageHolder ()
  {
  }

  public AfficherMessageHolder (Talk.AfficherMessage initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Talk.AfficherMessageHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Talk.AfficherMessageHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Talk.AfficherMessageHelper.type ();
  }

}
