package Talk;


/**
* Talk/AfficherMessageOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Talk.idl
* jeudi 3 novembre 2016 18 h 40 CET
*/

public interface AfficherMessageOperations 
{
  void afficherMessage (String message);
} // interface AfficherMessageOperations
