package Talk;


/**
* Talk/ChatOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Talk.idl
* jeudi 3 novembre 2016 18 h 40 CET
*/

public interface ChatOperations 
{
  void inscription (Talk.AfficherMessage client);
  void diffusion (String message);
} // interface ChatOperations
