/** 
 * Contrat IDL de chat
 *
 * @author Robin DEGIRONDE
 * @author Charles BANQUET
 * @author Rémi BARBASTE
 */
/************************************
* Contrat IDL de talk *
************************************/

module Talk {

    interface AfficherMessage {
       oneway void afficherMessage(in string message);
    };
    
    interface Chat{
    	oneway void inscription (in AfficherMessage client);
    	
    	oneway void diffusion (in string message);
    };
};

